# Generated by Django 3.1.7 on 2021-05-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('oldPass', models.CharField(max_length=100)),
                ('newPass', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ChangePassword',
            },
        ),
        migrations.CreateModel(
            name='ConservationRank',
            fields=[
                ('rankId', models.IntegerField(primary_key=True, serialize=False)),
                ('stateRank', models.CharField(max_length=100)),
                ('globalRank', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ConservationRank',
            },
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('statusId', models.IntegerField(primary_key=True, serialize=False)),
                ('federalStatus', models.CharField(max_length=100)),
                ('stateStatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ListingStatus',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureId', models.IntegerField(primary_key=True, serialize=False)),
                ('imageFile', models.ImageField(upload_to='')),
                ('plantId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
            options={
                'db_table': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='PlantLocation',
            fields=[
                ('plantId', models.IntegerField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PlantLocation',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('sightingId', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('plantId', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Sighting',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('subgroupId', models.IntegerField(primary_key=True, serialize=False)),
                ('taxSubgroup', models.CharField(max_length=100)),
                ('groupId', models.IntegerField()),
            ],
            options={
                'db_table': 'Subgroup',
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('groupId', models.IntegerField(primary_key=True, serialize=False)),
                ('taxGroup', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TaxGroup',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('joinDate', models.DateTimeField()),
                ('numSightings', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.IntegerField(primary_key=True, serialize=False)),
                ('commonName', models.CharField(max_length=100)),
                ('scientificName', models.CharField(max_length=100)),
                ('yearLastDocumented', models.CharField(max_length=100)),
                ('rankId', models.IntegerField()),
                ('subgroupId', models.IntegerField()),
                ('statusId', models.IntegerField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPageApp.taxgroup')),
            ],
            options={
                'db_table': 'Plant',
            },
        ),
    ]
